import type { CardDefinition } from './types';

export const CARD_LIBRARY: CardDefinition[] = [
  // ── OPCODES ─────────────────────────────────────────────────────────────────

  {
    id: 'OP-001',
    name: 'MOV',
    ascii: 'MOV AX, ??',
    cost: 1,
    rarity: 'common',
    description: 'Adjacent strike. Deal 4 damage.',
    tags: ['opcode', 'damage', 'adjacent'],
    target: 'enemy',
    range: { min: 1, max: 1 },
    effects: [{ type: 'damage', value: 4 }],
  },
  {
    id: 'OP-002',
    name: 'ADD',
    ascii: 'ADD ??, 5',
    cost: 1,
    rarity: 'common',
    description: 'Ranged packet. Deal 4 damage and apply Burn 2 for 2 turns.',
    tags: ['opcode', 'damage', 'burn', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 4 },
      { type: 'applyStatus', value: 2, duration: 2, status: 'burn', target: 'enemy' },
    ],
  },
  {
    id: 'OP-003',
    name: 'SUB',
    ascii: 'SUB ??, 3',
    cost: 1,
    rarity: 'common',
    description: 'Mid-range poke. Deal 3 damage, drain 1 enemy CPU, apply Vulnerable.',
    tags: ['opcode', 'damage', 'cpu', 'vulnerable'],
    target: 'enemy',
    range: { min: 1, max: 2 },
    effects: [
      { type: 'damage', value: 3 },
      { type: 'enemyCpuLoss', value: 1 },
      { type: 'applyStatus', value: 1, duration: 2, status: 'vulnerable', target: 'enemy' },
    ],
  },
  {
    id: 'OP-005',
    name: 'DEC',
    ascii: 'DEC ??',
    cost: 1,
    rarity: 'common',
    description: 'Melee breaker. Deal 4 damage and inflict Shield Break.',
    tags: ['opcode', 'damage', 'debuff', 'shield-break'],
    target: 'enemy',
    range: { min: 1, max: 1 },
    effects: [
      { type: 'damage', value: 4 },
      { type: 'enemyArmorBreak', value: 1 },
      { type: 'applyStatus', value: 1, duration: 2, status: 'shieldBreak', target: 'enemy' },
    ],
  },
  {
    id: 'OP-015',
    name: 'JMP',
    ascii: 'JMP 0xFF',
    cost: 1,
    rarity: 'common',
    description: 'Move up to 2 steps toward any hex.',
    tags: ['opcode', 'move'],
    target: 'self',
    range: { min: 0, max: 0 },
    effects: [{ type: 'moveSelf', value: 2 }],
  },
  {
    id: 'OP-016',
    name: 'CALL',
    ascii: 'CALL ??',
    cost: 1,
    rarity: 'common',
    description: 'Long-range call. Deal 3 damage and draw 1 card.',
    tags: ['opcode', 'damage', 'draw', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 4 },
    effects: [
      { type: 'damage', value: 3 },
      { type: 'draw', value: 1 },
    ],
  },
  {
    id: 'OP-018',
    name: 'NOP',
    ascii: 'NOP',
    cost: 0,
    rarity: 'common',
    description: 'No operation. Gain 1 CPU cycle.',
    tags: ['opcode', 'cpu'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [{ type: 'gainCpu', value: 1 }],
  },
  {
    id: 'OP-019',
    name: 'HLT',
    ascii: 'HLT',
    cost: 2,
    rarity: 'uncommon',
    description: 'Halt execution. Root the enemy and skip its next turn.',
    tags: ['opcode', 'control', 'root'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'applyStatus', value: 1, duration: 1, status: 'root', target: 'enemy' },
      { type: 'skipEnemyTurn', value: 1 },
    ],
  },
  {
    id: 'OP-020',
    name: 'INT',
    ascii: 'INT 0x80',
    cost: 2,
    rarity: 'uncommon',
    description: 'Broadcast interrupt. Select a hex; deal 5 damage and Burn 2 to all enemies within range.',
    tags: ['opcode', 'aoe', 'damage', 'burn', 'interrupt'],
    target: 'aoe',
    range: { min: 0, max: 2 },
    effects: [
      { type: 'damage', value: 5 },
      { type: 'applyStatus', value: 2, duration: 2, status: 'burn', target: 'enemy' },
    ],
  },
  {
    id: 'OP-006',
    name: 'PUSH',
    ascii: 'PUSH ??',
    cost: 1,
    rarity: 'common',
    description: 'Deal 2 damage and load 1 entry onto the stack. POP entries for burst.',
    tags: ['opcode', 'damage', 'stack', 'adjacent'],
    target: 'enemy',
    range: { min: 1, max: 2 },
    effects: [
      { type: 'damage', value: 2 },
      { type: 'stackPush', value: 1 },
    ],
  },
  {
    id: 'OP-007',
    name: 'POP',
    ascii: 'POP ??',
    cost: 1,
    rarity: 'uncommon',
    description: 'Detonate the stack. Deal 4 damage per stacked entry. Empty stack = no effect.',
    tags: ['opcode', 'damage', 'stack', 'burst'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [{ type: 'stackPop', value: 99 }],
  },
  {
    id: 'OP-012',
    name: 'SHL',
    ascii: 'SHL ??, 1',
    cost: 1,
    rarity: 'uncommon',
    description: 'Shift Left: arm the next card for ×2 damage and draw 1.',
    tags: ['opcode', 'buff', 'draw', 'amplify'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'onNextPlayDamage', value: 2 },
      { type: 'draw', value: 1 },
    ],
  },
  {
    id: 'OP-013',
    name: 'SHR',
    ascii: 'SHR ??, 1',
    cost: 1,
    rarity: 'common',
    description: 'Shift Right: deal 2 damage and drain 3 enemy CPU.',
    tags: ['opcode', 'damage', 'cpu', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 2 },
      { type: 'enemyCpuLoss', value: 3 },
    ],
  },
  {
    id: 'OP-021',
    name: 'MUL',
    ascii: 'MUL ??, 3',
    cost: 2,
    rarity: 'uncommon',
    description: 'Deal 6 damage. Deals 4 extra if your HP exceeds the enemy.',
    tags: ['opcode', 'damage', 'conditional', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 6 },
      { type: 'damage', value: 4, condition: { kind: 'playerHpMoreThanEnemy' } },
    ],
  },
  {
    id: 'OP-026',
    name: 'JZ',
    ascii: 'JZ 0x00',
    cost: 2,
    rarity: 'uncommon',
    description: 'Jump if Zero: deal 4 damage. If enemy CPU = 0, deal 8 bonus damage.',
    tags: ['opcode', 'damage', 'conditional', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 4 },
    effects: [
      { type: 'damage', value: 4 },
      { type: 'damage', value: 8, condition: { kind: 'enemyCpuZero' } },
    ],
  },
  {
    id: 'OP-031',
    name: 'JB',
    ascii: 'JB 0x00',
    cost: 2,
    rarity: 'uncommon',
    description: 'Jump if Below: restore 4 HP. Restores 8 extra if your HP is less than the enemy.',
    tags: ['opcode', 'heal', 'conditional'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'heal', value: 4 },
      { type: 'heal', value: 8, condition: { kind: 'playerHpLessThanEnemy' } },
    ],
  },
  {
    id: 'OP-033',
    name: 'CLC',
    ascii: 'CLC',
    cost: 2,
    rarity: 'common',
    description: 'Clear Carry: gain 3 armor.',
    tags: ['opcode', 'armor'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [{ type: 'armor', value: 3 }],
  },
  {
    id: 'OP-034',
    name: 'STC',
    ascii: 'STC',
    cost: 1,
    rarity: 'uncommon',
    description: 'Set Carry: cleanse all debuffs from self.',
    tags: ['opcode', 'cleanse', 'utility'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [{ type: 'cleanse', value: 99 }],
  },
  {
    id: 'OP-047',
    name: 'BSWAP',
    ascii: 'BSWAP ??',
    cost: 2,
    rarity: 'uncommon',
    description: 'Byte Swap: pull the enemy 2 hexes toward you.',
    tags: ['opcode', 'pull', 'position'],
    target: 'enemy',
    range: { min: 2, max: 4 },
    effects: [{ type: 'pull', value: 2 }],
  },

  // ── New Opcodes ──────────────────────────────────────────────────────────────

  {
    id: 'OP-036',
    name: 'XCHG',
    ascii: 'XCHG AX, BX',
    cost: 1,
    rarity: 'common',
    description: 'Exchange registers. Deal 3 damage and push enemy 1 hex.',
    tags: ['opcode', 'damage', 'push', 'position'],
    target: 'enemy',
    range: { min: 1, max: 2 },
    effects: [
      { type: 'damage', value: 3 },
      { type: 'push', value: 1 },
    ],
  },
  {
    id: 'OP-037',
    name: 'AND',
    ascii: 'AND ??, 0xFF',
    cost: 1,
    rarity: 'common',
    description: 'Bitwise AND: deal 2 damage and drain 2 enemy CPU.',
    tags: ['opcode', 'damage', 'cpu', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 2 },
      { type: 'enemyCpuLoss', value: 2 },
    ],
  },
  {
    id: 'OP-038',
    name: 'OR',
    ascii: 'OR ??, 0x01',
    cost: 0,
    rarity: 'common',
    description: 'Bitwise OR: gain 1 CPU and 1 armor.',
    tags: ['opcode', 'cpu', 'armor', 'utility'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'gainCpu', value: 1 },
      { type: 'armor', value: 1 },
    ],
  },
  {
    id: 'OP-039',
    name: 'XOR',
    ascii: 'XOR ??, ??',
    cost: 2,
    rarity: 'uncommon',
    description: 'Exclusive OR: deal 5 damage. +4 bonus if the enemy has any status effect.',
    tags: ['opcode', 'damage', 'conditional', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 5 },
      { type: 'damage', value: 4, condition: { kind: 'enemyHasStatus' } },
    ],
  },
  {
    id: 'OP-040',
    name: 'NOT',
    ascii: 'NOT ??',
    cost: 2,
    rarity: 'uncommon',
    description: 'Invert: deal 3 damage, apply Burn 3, and cleanse all your debuffs.',
    tags: ['opcode', 'damage', 'burn', 'cleanse'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 3 },
      { type: 'applyStatus', value: 3, duration: 2, status: 'burn', target: 'enemy' },
      { type: 'cleanse', value: 0 },
    ],
  },
  {
    id: 'OP-041',
    name: 'INC',
    ascii: 'INC ??',
    cost: 1,
    rarity: 'common',
    description: 'Increment: deal 2 damage, draw 1 card, gain 1 armor.',
    tags: ['opcode', 'damage', 'draw', 'armor'],
    target: 'enemy',
    range: { min: 1, max: 2 },
    effects: [
      { type: 'damage', value: 2 },
      { type: 'draw', value: 1 },
      { type: 'armor', value: 1 },
    ],
  },
  {
    id: 'OP-042',
    name: 'CMP',
    ascii: 'CMP AX, BX',
    cost: 1,
    rarity: 'uncommon',
    description: 'Compare: deal 2 damage. Apply Shield Break if your HP > enemy HP; else gain 3 armor.',
    tags: ['opcode', 'damage', 'conditional', 'adaptive'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 2 },
      { type: 'applyStatus', value: 1, duration: 2, status: 'shieldBreak', target: 'enemy', condition: { kind: 'playerHpMoreThanEnemy' } },
      { type: 'armor', value: 3, condition: { kind: 'playerHpLessThanEnemy' } },
    ],
  },
  {
    id: 'OP-043',
    name: 'LEA',
    ascii: 'LEA AX, [??]',
    cost: 1,
    rarity: 'uncommon',
    description: 'Load Effective Address: move up to 3 steps to any hex.',
    tags: ['opcode', 'move', 'range'],
    target: 'self',
    range: { min: 0, max: 0 },
    effects: [{ type: 'moveSelf', value: 3 }],
  },
  {
    id: 'OP-044',
    name: 'RET',
    ascii: 'RET',
    cost: 1,
    rarity: 'common',
    description: 'Return from subroutine. Draw 2 cards.',
    tags: ['opcode', 'draw', 'utility'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [{ type: 'draw', value: 2 }],
  },
  {
    id: 'OP-045',
    name: 'LOOP',
    ascii: 'LOOP 0x??',
    cost: 2,
    rarity: 'uncommon',
    description: 'Loop body: deal 3 damage per stack entry (minimum 3). Does NOT consume the stack.',
    tags: ['opcode', 'damage', 'stack', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [{ type: 'damagePerStack', value: 3 }],
  },
  {
    id: 'OP-046',
    name: 'JNZ',
    ascii: 'JNZ 0x??',
    cost: 1,
    rarity: 'common',
    description: 'Jump if Not Zero: deal 4 damage. +4 if enemy CPU > 0.',
    tags: ['opcode', 'damage', 'conditional', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 4 },
    effects: [
      { type: 'damage', value: 4 },
      { type: 'damage', value: 4, condition: { kind: 'enemyCpuAboveZero' } },
    ],
  },

  // ── PACKETS ─────────────────────────────────────────────────────────────────

  {
    id: 'DP-004',
    name: '0x0D',
    ascii: '0x0D \\r',
    cost: 1,
    rarity: 'common',
    description: 'Carriage Return: push enemy 1 hex away and restore 2 integrity.',
    tags: ['packet', 'push', 'heal'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'push', value: 1 },
      { type: 'heal', value: 2 },
    ],
  },
  {
    id: 'DP-005',
    name: '0x0A',
    ascii: '0x0A \\n',
    cost: 1,
    rarity: 'common',
    description: 'Line Feed: advance 1 step toward the enemy and gain 1 CPU.',
    tags: ['packet', 'move', 'cpu'],
    target: 'self',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'moveSelf', value: 1 },
      { type: 'gainCpu', value: 1 },
    ],
  },
  {
    id: 'DP-009',
    name: '0x80',
    ascii: '0x80 HIGH',
    cost: 2,
    rarity: 'uncommon',
    description: 'High Bit: gain 2 armor. Next card played deals double damage.',
    tags: ['packet', 'armor', 'buff'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'armor', value: 2 },
      { type: 'onNextPlayDamage', value: 2 },
    ],
  },
  {
    id: 'DP-023',
    name: '0xD15C',
    ascii: '0xD15C DISC',
    cost: 2,
    rarity: 'uncommon',
    description: 'Disc Error: apply Regen 3 for 3 turns, gain 1 armor.',
    tags: ['packet', 'regen', 'armor'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'regen', value: 3, duration: 3 },
      { type: 'armor', value: 1 },
    ],
  },

  // ── SYSTEM CALLS ─────────────────────────────────────────────────────────────

  {
    id: 'SC-003',
    name: 'kill()',
    ascii: 'kill(SIGKILL)',
    cost: 2,
    rarity: 'uncommon',
    description: 'SIGKILL: deal 10 damage and root the enemy for 1 turn.',
    tags: ['syscall', 'damage', 'root', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 10 },
      { type: 'applyStatus', value: 1, duration: 1, status: 'root', target: 'enemy' },
    ],
  },
  {
    id: 'SC-010',
    name: 'nice()',
    ascii: 'nice(-20)',
    cost: 2,
    rarity: 'uncommon',
    description: 'Renice to highest priority: gain 3 CPU cycles and 1 armor.',
    tags: ['syscall', 'cpu', 'armor', 'utility'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'gainCpu', value: 3 },
      { type: 'armor', value: 1 },
    ],
  },
  {
    id: 'SC-011',
    name: 'alarm()',
    ascii: 'alarm(3)',
    cost: 2,
    rarity: 'uncommon',
    description: 'Set a burn timer: apply Burn 4 to the enemy for 3 turns.',
    tags: ['syscall', 'burn', 'dot', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 4 },
    effects: [
      { type: 'applyStatus', value: 4, duration: 3, status: 'burn', target: 'enemy' },
    ],
  },
  {
    id: 'SC-013',
    name: 'pipe()',
    ascii: 'pipe(fd)',
    cost: 2,
    rarity: 'uncommon',
    description: 'Open pipeline: draw 2 cards. Next card played deals ×1.5 damage.',
    tags: ['syscall', 'draw', 'buff', 'combo'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'draw', value: 2 },
      { type: 'onNextPlayDamage', value: 1.5 },
    ],
  },
  {
    id: 'SC-020',
    name: 'fork()',
    ascii: 'fork()',
    cost: 2,
    rarity: 'uncommon',
    description: 'Spawn child process: draw 2 cards and gain 2 CPU.',
    tags: ['syscall', 'draw', 'cpu', 'utility'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'draw', value: 2 },
      { type: 'gainCpu', value: 2 },
    ],
  },
  {
    id: 'SC-021',
    name: 'mmap()',
    ascii: 'mmap(0,sz,RW)',
    cost: 2,
    rarity: 'uncommon',
    description: 'Map memory: gain 4 armor and Regen 2 for 3 turns.',
    tags: ['syscall', 'armor', 'regen', 'sustain'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'armor', value: 4 },
      { type: 'regen', value: 2, duration: 3 },
    ],
  },
  {
    id: 'SC-022',
    name: 'malloc()',
    ascii: 'malloc(4096)',
    cost: 0,
    rarity: 'rare',
    description: 'Allocate heap: draw 4 cards but take 6 damage. HIGH RISK.',
    tags: ['syscall', 'draw', 'risky', 'engine'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'draw', value: 4 },
      { type: 'selfDamage', value: 6 },
    ],
  },
  {
    id: 'SC-023',
    name: 'free()',
    ascii: 'free(ptr)',
    cost: 2,
    rarity: 'uncommon',
    description: 'Free memory: cleanse all debuffs and heal 10 HP.',
    tags: ['syscall', 'cleanse', 'heal', 'recovery'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'cleanse', value: 99 },
      { type: 'heal', value: 10 },
    ],
  },
  {
    id: 'SC-024',
    name: 'SIGTERM',
    ascii: 'kill(SIGTERM)',
    cost: 2,
    rarity: 'uncommon',
    description: 'Terminate signal: deal 3 damage, skip the enemy\'s next turn, draw 1 card.',
    tags: ['syscall', 'damage', 'control', 'draw'],
    target: 'enemy',
    range: { min: 1, max: 4 },
    effects: [
      { type: 'damage', value: 3 },
      { type: 'skipEnemyTurn', value: 1 },
      { type: 'draw', value: 1 },
    ],
  },
  {
    id: 'SC-025',
    name: 'chmod()',
    ascii: 'chmod(0777)',
    cost: 3,
    rarity: 'rare',
    description: 'Elevate permissions: gain 6 armor. Next card played deals ×3 damage.',
    tags: ['syscall', 'armor', 'buff', 'amplify'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'armor', value: 6 },
      { type: 'onNextPlayDamage', value: 3 },
    ],
  },

  // ── EXPLOITS ─────────────────────────────────────────────────────────────────

  {
    id: 'EX-019',
    name: 'OFF_BY_ONE',
    ascii: 'i <= n',
    cost: 1,
    rarity: 'common',
    description: 'Classic off-by-one error: gain 1 CPU, draw 1 card, and gain 1 armor.',
    tags: ['exploit', 'cpu', 'draw', 'armor', 'utility'],
    target: 'none',
    range: { min: 0, max: 0 },
    effects: [
      { type: 'gainCpu', value: 1 },
      { type: 'draw', value: 1 },
      { type: 'armor', value: 1 },
    ],
  },
  {
    id: 'EX-020',
    name: 'HEAP_SPRAY',
    ascii: 'heap[*]=0x41',
    cost: 2,
    rarity: 'uncommon',
    description: 'Spray heap addresses. Select a hex; apply Burn 2 for 2 turns to all enemies in range.',
    tags: ['exploit', 'aoe', 'burn', 'area'],
    target: 'aoe',
    range: { min: 0, max: 3 },
    effects: [
      { type: 'applyStatus', value: 2, duration: 2, status: 'burn', target: 'enemy' },
    ],
  },
  {
    id: 'EX-021',
    name: 'USE_AFTER_FREE',
    ascii: 'ptr->fn()',
    cost: 2,
    rarity: 'rare',
    description: 'Access freed memory: deal 5 damage. If the enemy has any status effect, deal 12 instead.',
    tags: ['exploit', 'damage', 'conditional', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 5 },
      { type: 'damage', value: 7, condition: { kind: 'enemyHasStatus' } },
    ],
  },
  {
    id: 'EX-022',
    name: 'DOUBLE_FREE',
    ascii: 'free(p);free(p)',
    cost: 2,
    rarity: 'uncommon',
    description: 'Double-free error: deal 6 damage twice.',
    tags: ['exploit', 'damage', 'double-hit'],
    target: 'enemy',
    range: { min: 1, max: 2 },
    effects: [
      { type: 'damage', value: 6 },
      { type: 'damage', value: 6 },
    ],
  },
  {
    id: 'EX-023',
    name: 'FORMAT_STR',
    ascii: 'printf(input)',
    cost: 2,
    rarity: 'rare',
    description: 'Format string exploit: drain 4 enemy CPU and deal 3 damage per drained CPU (12 total).',
    tags: ['exploit', 'cpu', 'damage', 'ranged'],
    target: 'enemy',
    range: { min: 1, max: 4 },
    effects: [
      { type: 'enemyCpuLoss', value: 4 },
      { type: 'damage', value: 12 },
    ],
  },
  {
    id: 'EX-024',
    name: 'BUFFER_OVERFLOW',
    ascii: 'strcpy(dst,src)',
    cost: 2,
    rarity: 'uncommon',
    description: 'Buffer overflow: deal 8 damage and push the enemy 2 hexes away.',
    tags: ['exploit', 'damage', 'push', 'position'],
    target: 'enemy',
    range: { min: 1, max: 2 },
    effects: [
      { type: 'damage', value: 8 },
      { type: 'push', value: 2 },
    ],
  },
  {
    id: 'EX-025',
    name: 'SEGFAULT',
    ascii: 'SIGSEGV',
    cost: 1,
    rarity: 'rare',
    description: 'Segmentation fault: take 6 damage yourself but deal 10 damage and push enemy 3 hexes.',
    tags: ['exploit', 'damage', 'push', 'risky'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'selfDamage', value: 6 },
      { type: 'damage', value: 10 },
      { type: 'push', value: 3 },
    ],
  },
  {
    id: 'EX-026',
    name: 'BIT_FLIP',
    ascii: 'mem ^= 0x01',
    cost: 1,
    rarity: 'common',
    description: 'Flip a bit: deal 3 damage and apply Burn 2. If enemy already has a status, deal 5 more.',
    tags: ['exploit', 'damage', 'burn', 'conditional'],
    target: 'enemy',
    range: { min: 1, max: 3 },
    effects: [
      { type: 'damage', value: 3 },
      { type: 'applyStatus', value: 2, duration: 2, status: 'burn', target: 'enemy' },
      { type: 'damage', value: 5, condition: { kind: 'enemyHasStatus' } },
    ],
  },
];

export function startingDeck(): CardDefinition[] {
  const byId = (id: string) => {
    const card = CARD_LIBRARY.find((c) => c.id === id);
    if (!card) throw new Error(`Card not found: ${id}`);
    return card;
  };
  return [
    byId('OP-001'), // MOV ×2
    byId('OP-001'),
    byId('OP-002'), // ADD
    byId('OP-003'), // SUB
    byId('OP-015'), // JMP
    byId('OP-016'), // CALL
    byId('OP-018'), // NOP
    byId('OP-038'), // OR (new cheap utility)
    byId('DP-004'), // 0x0D push
    byId('DP-005'), // 0x0A advance
  ];
}
